### ISSUE TITLE
建议ks.txt文件

### ISSUE THREAD

**Issue by auula** [WangRongsheng/beautiful#1]
>>建议ks.txt文件通过服务器程序爬取，然后设置一个定时器定时更新ks.txt全程自动化，在服务器端配置git仓库配置好github推送使用的ssh key,然后每隔30分钟进行推送更新ks.txt.
#### 想知道我是谁吗？bro😏

**Comment by WangRongsheng** [comment]
> > > 建议ks.txt文件通过服务器程序爬取，然后设置一个定时器定时更新ks.txt全程自动化，在服务器端配置git仓库配置好github推送使用的ssh key,然后每隔30分钟进行推送更新ks.txt.
> 
> #### 想知道我是谁吗？bro😏

QQ不够老哥闹挺了啊，哈哈~同样是90后，为什么哥哥那么优秀。
